import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex justify-between p-10">
          <p>Nimanshi</p>
          <div className="flex gap-4">
            <Link href={'/'}>Home</Link>
            <Link href={'/members'}>Members</Link>
            <Link href={'/payment'}>Payment</Link>
          </div>
        </nav>
        
        
        
        
        
        {children}

      </body>
    </html>
  );
}
